name: CRMGrow Development Build to s3
on:
  push:
    branches: [development]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2

      - name: Install NPM v12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'

      - name: NPM install...
        run: npm install

      - name: Build frontend
        run: node --max-old-space-size=8192 node_modules/@angular/cli/bin/ng build --prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Upload to AWS
        run: |
          aws s3 rm s3://crmgrow-development/ --recursive
          aws s3 cp dist/crmgrow s3://crmgrow-development/ --recursive --acl public-read

