name: TeamGrow Build to s3
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
  
      steps:
      - name: Project Checkout
        uses: actions/checkout@v2
        
      - name: Install NPM v8.11
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'   
        
      - name: NPM install...
        run: npm install 

      - name: Build frontend
        run: npm run build
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
  
      - name: Upload to AWS
        run: |
          output=$(aws cloudfront get-distribution-config  --id EFW5LJQM4RH8B | jq -r  .DistributionConfig.Origins.Items[0].DomainName)
          echo $output
          if [[ $output ==  'teamgrow-staticsite-blue.s3-website-us-west-1.amazonaws.com' ]]
          then
          aws s3 rm s3://teamgrow-staticsite-green/ --recursive 
          aws s3 cp dist s3://teamgrow-staticsite-green/ --recursive --acl public-read
          elif [[ $output ==  'teamgrow-staticsite-green.s3-website-us-west-1.amazonaws.com' ]]
          then
          aws s3 rm s3://teamgrow-staticsite-blue/ --recursive 
          aws s3 cp dist s3://teamgrow-staticsite-blue/ --recursive --acl public-read
          fi 
